version: 2

jobs:
  build-app-dist:
    docker:
      - image: openjdk:8
    steps:
      - checkout
      - run:
          command: |
            {
              md5sum gradle/wrapper/gradle-wrapper.properties
              md5sum settings.gradle
              md5sum $(find . -name 'build.gradle')
            } > ~/cache-key-source-gradle
      - restore_cache:
          key: gradle-{{ checksum "~/cache-key-source-gradle" }}
      - run:
          name: Build
          command: |
            ./gradlew --no-daemon build
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
          key: gradle-{{ checksum "~/cache-key-source-gradle" }}
      - persist_to_workspace:
          root: ~/project
          paths:
            - app/build/distributions

  build-docker-image-and-test:
    docker:
      - image: docker:git
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      # To enable `docker` command and `docker-compose` command on Docker Executor
      # https://circleci.com/docs/2.0/building-docker-images/
      - setup_remote_docker:
          version: 17.11.0-ce
      - run:
          name: Build Docker image
          command: docker build -t sbs-app app

      - run:
          background: true
          command: |
            set +e
            docker run -it --rm -p 8080:8080 --name sbs-app-test sbs-app
            s=$?
            # Java application terminated by signal returns exit code 143
            if [ $s -eq 0 -o $s -eq 143 ]; then exit 0; else exit $s; fi
      - run:
          name: Wait for Application
          command: sleep 3
      - run:
          command: |
            docker build -t sbs-system-test system-test
            docker run -it --rm --network=host --name sbs-system-test sbs-system-test
      - run:
          when: always
          command: docker stop sbs-app-test

workflows:
  version: 2
  build:
    jobs:
      - build-app-dist
      - build-docker-image-and-test:
          requires:
            - build-app-dist
