version: 2

jobs:
  build:
    docker:
      - image: openjdk:8
    steps:
      - checkout
      - run:
          command: |
            {
              md5sum gradle/wrapper/gradle-wrapper.properties
              md5sum settings.gradle
              md5sum $(find . -name 'build.gradle')
            } > ~/cache-key-source-gradle
      - restore_cache:
          key: gradle-{{ checksum "~/cache-key-source-gradle" }}
      - run:
          name: Install
          command: |
            ./gradlew --no-daemon installDist
      - run:
          name: Run and test
          command: |
            ./app/build/install/app/bin/app > result
            test "$(cat result)" = "Hello world!"
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
          key: gradle-{{ checksum "~/cache-key-source-gradle" }}

workflows:
  version: 2
  build:
    jobs:
      - build
