version: 2

jobs:
  build-app-dist:
    docker:
      - image: openjdk:8
    steps:
      - checkout
      - run:
          command: |
            {
              md5sum gradle/wrapper/gradle-wrapper.properties
              md5sum settings.gradle
              md5sum $(find . -name 'build.gradle' | sort -)
            } > ~/cache-key-source-gradle
      - restore_cache:
          key: gradle-{{ checksum "~/cache-key-source-gradle" }}
      - run:
          name: Build
          command: |
            ./gradlew --no-daemon build
      - run:
          name: Report code coverage
          command: |
            bash <(curl -s https://codecov.io/bash)
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
          key: gradle-{{ checksum "~/cache-key-source-gradle" }}
      - store_test_results:
          path: modules/db-access/build/test-results
      - store_test_results:
          path: modules/ktor-twitter-login/build/test-results
      - store_test_results:
          path: modules/whatwg-url/build/test-results
      - store_test_results:
          path: modules/sbs-main/build/test-results
      - persist_to_workspace:
          root: ~/project
          paths:
            - app/build/distributions

  build-docker-image-and-test:
    docker:
      - image: docker:git
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      # To enable `docker` command and `docker-compose` command on Docker Executor
      # https://circleci.com/docs/2.0/building-docker-images/
      - setup_remote_docker:
          version: 17.11.0-ce
      - run:
          name: Build Docker image
          command: docker build -t sbs-app app
      - run:
          name: Build Docker image for system test
          command: docker build -t sbs-system-test system-test
      - run:
          command: docker pull quay.io/wakaba/firefoxdriver:stable

      - run:
          background: true
          command: |
            set +e
            docker run -it --rm -p 8080:8080 \
                -e "SBS_CONTEXT_URL=http://localhost:8080" \
                -e "SBS_SESSION_ENCRYPTION_KEY=0123456789ABCDEF" \
                -e "SBS_SESSION_SIGN_KEY=01234567" \
                -e "SBS_TWITTER_CLIENT_IDENTIFIER=TEST_IDENTIFIER" \
                -e "SBS_TWITTER_CLIENT_SECRET=TEST_SHARED_SECRET" \
                --name sbs-app-test sbs-app
            s=$?
            # Java application terminated by signal returns exit code 143
            if [ $s -eq 0 -o $s -eq 143 ]; then exit 0; else exit $s; fi
      - run:
          background: true
          command: docker run -it --rm --network=host --name sbs-wd-firefox quay.io/wakaba/firefoxdriver:stable /fx
      - run:
          name: Wait for test enviroment
          command: sleep 3
      - run:
          name: Run system test
          command: docker run -it --rm --network=host --name sbs-system-test sbs-system-test
      - run:
          when: always
          command: docker stop sbs-wd-firefox
      - run:
          when: always
          command: docker stop sbs-app-test

workflows:
  version: 2
  build:
    jobs:
      - build-app-dist
      - build-docker-image-and-test:
          requires:
            - build-app-dist
